### ISSUE TITLE
Proposal: `Asyncify`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#126]
Many Node.js packages ([example](https://github.com/sindresorhus/make-dir)) expose both an async and sync API. Usually, the only difference type-wise is that the async versions' return value is wrapped in a `Promise`. It would be useful if the type definition could be reused, so you could just take the definition for the sync version and wrap it in `type FooAsync = Asyncify<FooSync>`.

**Comment by brodybits** [comment]
My impression of Node.js was that there is a bigger difference between async and sync API: https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/

**Comment by sindresorhus** [comment]
Can you be more specific? We're talking about TS types, not how the APIs actually work.

**Comment by brodybits** [comment]
My apologies, I think I misread the description.

To really break it down: `FooSync` is the type of the synchronous function with arguments and return value types declared, with no promise, and `Asyncify<FooSync>` would be the same but with the return value type wrapped in a Promise.

So this is correct:

> Usually, the only difference type-wise is that the async versions' return value is wrapped in a `Promise`.

I think it is obvious to us that the implementation would have to be different, though, for the async version to be non-blocking. I think you know this may not be obvious to beginners, and I think we can all see beginners learning all kinds of things out of order in the JavaScript ecosystem. :=O

That said, I start to wonder about a couple of things, hopefully not too far off-topic:

- How useful would a sync API implementation really be as more and more programs start to use `async` and `await` keywords?
- Would it be possible to support some kind of generic programming so that the same code could work with both sync (blocking) and non-blocking async? Or would this be too impractical for consideration?

Thanks!

**Comment by fox1t** [comment]
I think this would be a nice addition.

**Comment by sindresorhus** [comment]
> How useful would a sync API implementation really be as more and more programs start to use async and await keywords?

We've had async programming since JavaScript was first released. `await` only makes it more readable. It doesn't change the fact that sometimes synchronousity makes sense. For example, in Node.js, synchronous file reads/writes are much faster for serial reads/writes than async. The benefit of async is that it enables concurrency even though JS is single-threaded. Command-line tools are also usually fine having a lot of synchronicity.

> Would it be possible to support some kind of generic programming so that the same code could work with both sync (blocking) and non-blocking async? Or would this be too impractical for consideration?

This question is not really relevant here as this is about types, not implementation. But to answer it, you could only share the parts that are not using `await`, for example, extracting some logic in to functions that are used by both implementations. Supporting both async and sync does come with some duplicate code and boilerplate, but it's worth it.
