### ISSUE TITLE
Suggestion: NonEmptyArray

### ISSUE THREAD

**Issue by danielepolencic** [sindresorhus/type-fest#14]
The following type looks really interesting:

```typescript
type NonEmptyArray<A> = A[] & {0: A};
```

The original discussion was brought up in this thread: https://github.com/gcanti/fp-ts/issues/735

If there's interest I could raise a PR.

**Comment by BendingBender** [comment]
Sounds very interesting and useful.

On the original discussion thread, they actually propose a different version of it with overloaded `map` function. The issue is that this type on its own has limited usefulness. Without an actual implementation for a conversion function (`<T>(array: T) => array is NonEmptyArray<T>`) one would always end up with a plain array after mapping it.

So this seems a little out of scope for this project.

**Comment by danielepolencic** [comment]
Gotcha. My thinking was more around function arguments:

```typescript
function Hello(array: NonEmptyArray<string>) {
  /* body */
}
```

**Comment by BendingBender** [comment]
Yeah, it just happened yesterday that I needed a type like this. The problem is ergonomics: Where do you get a value of this type from? Imagine an API like this:
```ts
function hello(array: NonEmptyArray<string>) {
  /* body */
}
```
Now you want to use it:
```ts
hello(['foo']); // => Works

const arr = ['foo'];
if (arr[0] != null) {
	hello(arr); // => Error
}
if (arr.length > 0) {
	hello(arr); // => Error
}
```
So when you use it with a literal or tuple type, this will work fine. But as soon as you have a plain array type this will fail although we have an element or a `length` check. So there is actually limited purpose of this type alone. To preserve developer ergonomics you actually need to provide a type guard:
```ts
function isNonEmptyArray<T>(array: T): array is NonEmptyArray<T> {
	return arr[0] != null;
}
```
Otherwise every user of this type will have to re-implement this function. But it is currently outside of the scope of this project to provide imlementations like the one above.

**Comment by danielepolencic** [comment]
👍
