### ISSUE TITLE
Property 'observable' does not exist on type 'SymbolConstructor'

### ISSUE THREAD

**Issue by tonyxiao** [sindresorhus/type-fest#19]
Getting the following error right after adding type-fest package

![image](https://user-images.githubusercontent.com/696842/55591922-bfff6580-56eb-11e9-9fe6-50732dfa77a8.png)

**Comment by BendingBender** [comment]
The problem is that the type definitions rely implicitly on node types. You can solve your problem by adding `@types/node` to your project. Alternatively, you can use the `skipLibCheck` compiler option.

@sindresorhus This is however an actual issue that we have to solve. We could rely on `@types/node` but then would have to add it as a project dependency. I don't think that it would be very obvious for users that they have add `@types/node` themselves as soon as they start unsing this lib.

An alternative would be to manually extend the global `Symbol` interface with the missing symbol, this way we could leave the package dependency-free.

What do you think?

**Comment by tonyxiao** [comment]
I have `@types/node` but pinned at version `8.10` because we're using node version 8.10 (highest supported version by default) on aws lambda. So even if we have `@types/node` this doesn't actually solve the issue. I think it's worth manually extending the global `Symbol` interface w/ this and add a comment to warn user of possible consequence.

**Comment by sindresorhus** [comment]
> An alternative would be to manually extend the global Symbol interface with the missing symbol, this way we could leave the package dependency-free.

👍
