### ISSUE TITLE
MergeExclusive is broken when used together with Except or built-in Omit

### ISSUE THREAD

**Issue by natalya-kim** [sindresorhus/type-fest#200]
## Environment

```ts
{
  "typescript": "4.2.4",
  "type-fest": "1.0.2"
}
```

## Problem

MergeExclusive is broken when used together with Except or the built-in Omit

## How to reproduce

```ts
import type * as TF from "type-fest"
type a = TF.MergeExclusive<{ a: boolean }, { b: boolean}> & { c: boolean }
type b = Omit<a, "c">

const c: b = {
  a: true,
  b: true
}
```

## Screenshots

<details><summary>Click to see the screenshots</summary>

<img width="666" alt="Screen Shot 2021-04-16 at 7 41 42 PM" src="https://user-images.githubusercontent.com/37357918/115033427-414d7d80-9eec-11eb-85ff-9aa5aac1e592.png">
<img width="655" alt="Screen Shot 2021-04-16 at 7 43 15 PM" src="https://user-images.githubusercontent.com/37357918/115033433-43afd780-9eec-11eb-808b-b6b62724a0e0.png">

</details>

**Comment by sindresorhus** [comment]
Do you have `"strict": true` enabled in your TS config?

**Comment by natalya-kim** [comment]
@sindresorhus thank you for the reply.
Yes, I do.

This is my `tsconfig.json`:

```json
{
  "exclude": ["**/node_modules", "**/.git", "**/dist", "**/tmp"],

  "compilerOptions": {
    "noEmit": true,
    "moduleResolution": "Node",
    "allowSyntheticDefaultImports": true,
    "allowJs": false,
    "checkJs": false,
    "skipLibCheck": true,

    "lib": ["esnext", "dom"],
    "module": "esnext",
    "target": "esnext",

    "sourceMap": true,
    "jsx": "react",
    "forceConsistentCasingInFileNames": true,
    "importHelpers": false,
    "resolveJsonModule": true,

    "strict": true,
    "noImplicitAny": false,
    "noUnusedLocals": false, // optimization happens during build
    "noUnusedParameters": false, // optimization happens during build

    "suppressImplicitAnyIndexErrors": true,

    "noEmitHelpers": true,
    "noErrorTruncation": true,
    "experimentalDecorators": true,

    "assumeChangesOnlyAffectDirectDependencies": true
  },

  "watchOptions": {
    // Use native file system events for files and directories
    "watchFile": "useFsEventsOnParentDirectory",
    "watchDirectory": "useFsEvents",

    // Poll files for updates more frequently
    // when they're updated a lot.
    "fallbackPolling": "dynamicPriority"
  }
}
```

**Comment by sindresorhus** [comment]
Hmm, this seems to me like a TypeScript limitation. It flattens the type when using `Omit`.

I have made a playground if anyone wants to help debug this: https://www.typescriptlang.org/play?ts=4.2.3&ssl=16&ssc=1&pln=16&pc=2#code/C4TwDgpgBA6glsAFgewK7ADwDE4CcDOwAKuBADRQDKEAxsgHYAmJkAfFALxQDeA2gNIQQLaHHpQAogA8aAG1SMIGANZDkAMyg4CxUhVUgNVWg2alWAXQD8ALij0IANwi4AvgG4AUJ9CQoAWRcAcwhpOVR8OGdsPEIRCmo6JhF2Dk8ASAAKbTjSKAAfYySzSABKKAgpYAgmfChkACMAK1pgKCsMrPgkNEwc3UgEk2TzKAAyItMRcsLM7pR0DESpvS1YgYh2Cf7pqBtOnbzC5ZHIL28fPIBDTgDg0Jl5SOjuKCu7BuRkWQgr8VcKK8Gh8vj8-q4tjwoDQQd9fv9Ln4GrcAPIAWwQGCuFAARDQcaxvElCNCPrduJ4oG87MBcKhyJSoMCoLT6Z5XEA

It might also be worth asking in https://github.com/Microsoft/TypeScript/issues/14094 where the type was inspired from.

**Comment by skarab42** [comment]
@natalya-kim @sindresorhus Seems to work with `Except` [Playground](https://www.typescriptlang.org/play?ts=4.2.3#code/JYWwDg9gTgLgBDAnmApnA3gUQB4GMVgwA0cAsilAOYo64A2ArgM7ABuKAvnAGZQQhwARElQBabiiYxBAbgBQckWgBiECHAC8ZCtVqMW7ADzoAhgC44AIzV0UJgHYcS6SxesRbDjgD44AMgxcNxs7R3kAenCMOUi4OJMAfgsGewATFG5gexRUiKi41ysQhzy4uCCij1DSrgAfaNiCpLgU9Mzs3Jj8uHNKz3tSuIr3fpqFJThVCAB5EGB4LVn5wymSAHJcNe9S9C6yxOCqhzh61oysnMGrZpHQk5a0846xxWQVNVoCBbhPwhW1EiCXCCbx7XaNHrNM7tS57AqHUZ7OoNbqWKGPGGdCG9W4lJEKXAQexSHhqJYwCxTcmaaLxCwwKAMFBEOTwhCMlByDgEokk7gfPBfSkC-CEGm7OnspkstkMplcuRAA).

**Comment by skarab42** [comment]
@sindresorhus  The PR #263 introduced in v2.3.2 fix the issue with `Expect` and `MergeExclusive` ([Playground](https://www.typescriptlang.org/play?ts=4.2.3#code/JYWwDg9gTgLgBDAnmApnA3gUQB4GMVgwA0cAsilAOYo64A2ArgM7ABuKAvnAGZQQhwARElQBabiiYxBAbgBQckWgBiECHAC8ZCtVqMW7ADzoAhgC44AIzV0UJgHYcS6SxesRbDjgD44AMgxcNxs7R3kAenCMOUi4OJMAfgsGewATFG5gexRUiKi41ysQhzy4uCCij1DSrgAfaNiCpLgU9Mzs3Jj8uHNKz3tSuIr3fpqFJThVCAB5EGB4LVn5wymSAHJcNe9S9C6yxOCqhzh61oysnMGrZpHQk5a0846xxWQVNVoCBbhPwhW1EiCXCCbZ7XaNHrNM7tS57AqHUZ7OoNbqWKGPGGdCG9W4lJEKXAQexSHhqJYwCxTcmaaLxCwwKAMFBEOTwhCMlByDjyOSE4nwbgfPBfSlC-CEGm7OnspkstkMplcnmxABqFBYRLghjgACYAHQAZj1OrgAAsYDAwEwzJFKPNTQxLHrCSBwiw0lBJNAHUxwkpxJIYOEwAw6HRwjqAGwG16oODTOipX4wQzTSwAKxQuBgABU3iQANIoRBMPNxlDYGAoNJMOAAa2LEG48YzWdzb18WgACsBcHXU63s2XmT88Ix0oYG4gmy3M0P83AiyXh95QbH3jNE8maQmk8K-qshMC13ySYLN3vxRTJmSt-vvlKevSOXKrM-FdyCUSmFU9XQIJQAAU57kiQ57JmBt6Xl8ACUMhAA)) and since `Omit` does not support it natively, there is nothing we can do,  then I close this issue.
