### ISSUE TITLE
Add @category JSDoc tag to improve reference docs generation

### ISSUE THREAD

**Issue by schickling** [sindresorhus/type-fest#203]
When generating reference docs (e.g. via [Paka](https://www.paka.dev/npm/type-fest) 🦙) it can be very helpful to mark exports with the `@category` JSDoc tag which enables grouping them in a semantically more meaningful way.

Here are a few example packages which already added the `@example` JSDoc tag:
- [graphql-ws](https://www.paka.dev/npm/graphql-ws)
- [@antfu/utils](https://www.paka.dev/npm/@antfu/utils)

**Comment by kirillgroshkov** [comment]
Sorry for offtopic, @schickling, do you know how I can get my packages listed on paka.dev? https://paka.dev doesn't show much and I can't even google-find anything about this Paka (which looks like a fantastic tool that I'd use!)

**Comment by schickling** [comment]
> Sorry for offtopic, @schickling, do you know how I can get my packages listed on paka.dev? https://paka.dev doesn't show much and I can't even google-find anything about this Paka (which looks like a fantastic tool that I'd use!)

Paka is not yet officially launched but currently in the process of increasing its feature and package coverage. If you're interested in using Paka I'd be excited to chat more. Maybe you want to [send me a DM on Twitter](https://twitter.com/schickling)?

**Comment by schickling** [comment]
> Either because it has a space in the name or because the type is conditional:
> 
> https://github.com/sindresorhus/type-fest/blob/9f4817edbe6b92a67eed9c320b9949b8552f5a53/package.json#L44-L50
> 
> Paka should show all types and assume the latest TypeScript version.

That's a great point @sindresorhus. Seems like Paka doesn't yet support `typesVersions` properly. Will be fixed soon! 🤞

**Comment by jasonkuhrt** [comment]
TS 4.5 has some improvements coming that will make distinguishing different kinds of `any` (explicitly written by author, failed to resolve, etc.) better. It _might_ help, but yeah, we've currently hit some relatively high walls with TS on this issue. The problem is that solving this is a combination of the AST + type checker, as the typechecker alone does not preserve info about the `any` such as where it is in the AST or how it came to be (again TS 4.5 might improve this). The consequence is that deep in our recursion we need to bring in AST info where currently today we have none. Its a big architectural change to start to tackle this in a general way. What we have today is some special-cases paths, but far from general solution (we discovered later how hard general would be).

Hope that makes sense.

**Comment by jasonkuhrt** [comment]
In VSC the same thing happens unless you have run npm install. We don't do that during extraction on the basis that doing so is too heavy in a request context.
