### ISSUE TITLE
Possible improvement of Omit

### ISSUE THREAD

**Issue by rifler** [sindresorhus/type-fest#23]
```typescript
type Omit<ObjectType, Keys> = Pick<
    ObjectType,
    Exclude<keyof ObjectType, Keys extends Primitive ? Keys : keyof Keys>
>
```

Example:
```typescript
// Primitive example
type A = Omit<{ a: 1, b: 2, c: 3 }, 'a' | 'b'>
// => { c: 3 }

// Object example
type B = Omit<{ a: 1, b: 2, c: 3 }, {a: true, b: 'a'}>
// => { c: 3 }
```

What do you think?

**Comment by rifler** [comment]
Hi there

**Comment by sindresorhus** [comment]
```ts
// Object example
type B = Omit<{ a: 1, b: 2, c: 3 }, {a: true, b: 'a'}>
// => { c: 3 }
```

I would have expected it to not omit anything as the items don't match the source object. Matching just by keys and not also by value is not expected behavior, at least for me.

If we accept it like this, it should probably be a separate helper.

We could consider supporting this with matching both key and value, but I'm not sure when that would be useful. Can you provide some real-world use-cases?

**Comment by sindresorhus** [comment]
Actually, you can easily do this with the current `Omit` type:

```ts
type B = Omit<{a: 1, b: 2, c: 3}, keyof {a: true, b: 'a'}>
// => {c: 3}
```

**Comment by sindresorhus** [comment]
> Can you provide some real-world use-cases?

@rifler :arrow_up:

**Comment by rifler** [comment]
> Can you provide some real-world use-cases?

No, you example with `keyof` is enough
