### ISSUE TITLE
`Jsonify` recursive cast properties of Date instead of cast to string

### ISSUE THREAD

**Issue by leosuncin** [sindresorhus/type-fest#256]
The following code is not transformed in a correct form

```typescript
import type { Jsonify } from 'type-fest';

interface Product {
  title: string;
  price: number;
  category: string;
  description: string;
  image: string;
  createdAt: Date;
  updatedAt: Date;
}

type ProductJson = Jsonify<Product>;
```

![Example error](https://user-images.githubusercontent.com/4307697/131237457-147336b3-8467-401a-89e8-1beb9217ecea.png)

I will expect that properties of type `Date` are converted to `string`, and I suspect that the problem is here

https://github.com/sindresorhus/type-fest/blob/6de66eb8c26cd37adda7213cdbfb5e8246af8328/source/jsonify.d.ts#L52-L54

**Comment by leosuncin** [comment]
What I want is a type when `stringify` a value then `parse` it, so the new value is still typed with the correct type  
  
```typescript
const product: Product = {
  title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
  price: 109.95,
  description: 'Your perfect pack for everyday use and walks in the forest.',
  category: "men's clothing",
  image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
  createdAt: new Date(),
  updatedAt: new Date(),
};

const jsonValues: Jsonify<Product> = JSON.parse(JSON.stringify(product));
```

**Comment by sindresorhus** [comment]
// @darcyparker

**Comment by darcyparker** [comment]
`Jsonify` does not transform a `Date` type to `string type because `Date` is not valid `JSON`.

`Product` must be valid `JSON` to `Jsonify` it... And by inspection it is not JSON because it contains `Date`.  `Jsonify` applies to interfaces that are `JSON`.  It transforms an `interface` into a `type` so that it can be structurally compared to `JsonValue`.  Interfaces cannot be structurally compared to a type because an interface can be re-opened to add properties that may not be satisfy `JsonValue`.

While its true that `JSON.stringify()` can serialize `Date` to a string. `JSON.parse()` is not an inverse because it does not parse the ISO8601String back to `Date`.

For your use case, you either:
* need something different than `JSON.parse()` that understands to inspect `string` to see if it is an ISO8601 string and if so, parse it back to `Date`. (And then you don't need `Jsonify<Product>`)
* Or you need something similar to but different than `Jsonify` that handles transforming a `Date` or nested `Date` to a string.
   * Maybe call it perhaps `JsonifyJsonWithDate`?

**Comment by darcyparker** [comment]
I think I can prototype something that does what you want... and will create a pull request early this week.... 

Basically it will be like `Jsonify`... but if it comes across a type that is not `JsonValue`, it will check if it `extends {[toJSON: infer J}` and if `J` is `JsonValue`, then use `J`.

Right now I am on the fence if `Jsonify` should be updated... or if it should be a new type.  I need to think about that more.
