### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by mohsen1** [sindresorhus/type-fest#3]
FYI https://github.com/piotrwitek/utility-types is very similar to this project.

**Comment by sindresorhus** [comment]
There are many similar projects, but they all have a lot of stuff that is theoretically cool, but that at least I, would never use in practice. I'm not trying for this to be the "Lodash of TS types". I just want to consolidate the most common types I need.

**Comment by inad9300** [comment]
A few others...
- https://github.com/andnp/SimplyTyped
- https://github.com/gcanti/typelevel-ts
- https://github.com/pelotom/type-zoo
- https://github.com/tycho01/typical

If what makes yours different is that it suits *you* specifically, you should clarify that in the README file so that people don't get confused by the project's goals.

**Comment by Offirmo** [comment]
Also: https://github.com/krzkaczor/ts-essentials
