### ISSUE TITLE
Get type should be able to return never so it can be used in a conditional type

### ISSUE THREAD

**Issue by joseDaKing** [sindresorhus/type-fest#315]
Get type should be able to return never so it can be used in a conditional type or a new generic type could be created.

```ts

type A<T> = Get<T, "items"> extends unkown ? "true" : "false"; //Will allways yield true
 ```

**Comment by sindresorhus** [comment]
@asbjornh Thoughts on this?

**Comment by asbjornh** [comment]
Yeah! The `extends` check in the above example is in the wrong order. The following is likely what OP is looking for:

```ts
type A<T> = unknown extends Get<T, "items"> ? true : false;
```

Explanation:
Conditional types can make a bit more intuitive sense if you read `extends` as "is a subtype of" or "is assignable to". 
F. ex., the above example is asking the question "is `Get<T, "items">` assignable to `unknown`?". Since _all_ types in TS are assignable to `unknown`, the answer is yes, no matter what the result of `Get<T, "items">` is.

If you flip it you get the question "is `unknown` assignable to `Get<T, "items">`?". Since `unknown` is only assignable to `unknown` and `any` (at least to my knowledge), the answer to this question is `true` if `Get<T, "items">` evaluates to `unknown` or `any`, or `false` otherwise.

**Comment by asbjornh** [comment]
@joseDaKing Did the above resolve your issue? Can this be closed?

**Comment by joseDaKing** [comment]
It resolved the issue thanks

**Comment by asbjornh** [comment]
Great! 😄
