### ISSUE TITLE
Proposal: Promisable

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/type-fest#40]
Some times we are just awaiting a function, so we don't really care if the returned value is actually a promise or not. With `Promisable`:

```ts
type Promisable<T> = T | Promise<T>;
```

One could write this:

```ts
type Foo = () => Promisable<string | number | null>
```

Rather than:

```ts
type Foo = () => string | number | null | Promise<string> | Promise<number> | Promise<null>
```

It helps write a bit cleaner code. I'm not sure if it's useful enough to be included here, but I thought I'd mention it.

**Comment by kainiedziela** [comment]
I'd be happy to integrate this.

**Comment by WORMSS** [comment]
This could also be quite nice for Promise.all style arguments.

**Comment by sindresorhus** [comment]
Accepted on the condition that someone opens an issue on TypeScript requesting it be added as a built-in, and comments the link to the issue here. I think it's a very common need.

For anyone that wants to tackle this, please read [guide for adding a type](https://github.com/sindresorhus/type-fest/blob/master/.github/contributing.md) and also see how the last type was added: https://github.com/sindresorhus/type-fest/commit/22c3a99f3005605d91feedcf667fda2bac279013 (Note the extensive docs and comments).

**Comment by fabiospampinato** [comment]
> Accepted on the condition that someone opens an issue on TypeScript requesting it be added as a built-in, and comments the link to the issue here. I think it's a very common need.

👍 https://github.com/microsoft/TypeScript/issues/32220
