### ISSUE TITLE
`Exact` does not work with `Opaque` after 2.19.0

### ISSUE THREAD

**Issue by eugene-mohc** [sindresorhus/type-fest#508]
`Exact` no longer works when there are any object properties which have a type created using `Opaque`. This used to work using version 2.18.0 and lower.

```ts
type SpecialName = Opaque<string, "special name">;

type OnlyAcceptName = {
  name: SpecialName;
};

function onlyAcceptNameImproved<T extends Exact<OnlyAcceptName, T>>(args: T) {}

onlyAcceptNameImproved({
  // Error: Type 'SpecialName' is not assignable to type 'never'
  name: "name" as SpecialName
});
```

Example using type-fest 2.18.0: https://codesandbox.io/s/twilight-shape-bc391p?file=/src/index.ts

Same example using latest version: https://codesandbox.io/s/boring-morse-96egn3?file=/src/index.ts

**Comment by sindresorhus** [comment]
Most likely this change: https://github.com/sindresorhus/type-fest/commit/edcad045569a2275a9957b4ce8f209783ecbf945

**Comment by sindresorhus** [comment]
// @zorji

**Comment by zorji** [comment]
Sorry for the late reply. Let me have a look.

**Comment by zorji** [comment]
Hi @eugene-mohc 

Sorry I am not familiar with `Opaque` type and what's its use case but looks like it's trying to solve a similar issue that this `Exact` type was trying to solve. By reading the definition of Opaque type, I am not sure whether it's because the internal details are hidden so it's not accessible and compare.

I am wondering whether the solution to check if it's an Opaque type and return the type as it is can solve the issue.

Would you able to checkout the change in this branch and see if that fixes the issue for you? https://github.com/sindresorhus/type-fest/pull/525
