### ISSUE TITLE
Unable to use `Opaque<Record<a, b>, c>`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/type-fest#708]
I think this is a limitation of TypeScript rather than the type's, but I wanted to document it here and see if anyone can come up with a solution. I think the issue is specifically because the `Record` only accepts `string` and is unable to accept the `[tag]` symbol in the union.

```ts
import {Opaque} from "type-fest";

type CustomString = Opaque<string, 'custom'>;
const string: CustomString = 'hello' as CustomString;
// ✅

type CustomObject = Opaque<{foo: 'bar'}, 'custom'>;
const object: CustomObject = {foo: 'bar'} as CustomObject;
// ✅

type CustomRecord = Opaque<Record<string, string>, 'custom'>;
const record: CustomRecord = {foo: 'bar'} as CustomRecord;
// ❌ Conversion of type '{ foo: string; }' to type 'CustomRecord' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
//  Property '[tag]' is missing in type '{ foo: string; }' but required in type 'TagContainer<"custom">'.(2352)

const emptyRecord: CustomRecord = {} as CustomRecord;
// ✅ 🤷‍♂️ 
```

[TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwPJgIYEcCuBTAvnAMyghDgCIYBPMbAWgOwGcYyBuAKHaprgGFNmJAMowowAHYBzOAF44KDDgA8zMVIA0cAOQBjATBJaAfBx0RxzOKomSAXH33DRN2doAW2ADaeIWuKkYHQRARNUkOAHoIuEBQck5ubCCDECQAIwArbB14OQUsbCUEAggIey1U1CgtXE1dRxBjU3NLCAysmHt+YLTM7NcikrKKqvwApJIe9sjouK5qRK7kgCUs6AATVzzlFbMoNZVnDStDySNavWDG9jMLeChVvc76nfX+4tLtYer-QMWSF720zggBlyPjmABu2CgjGA5jgEAIcAS2gQhEGxzCrDguD8BiR820fxAALWfhAqEocFSiVQcBAwGYqAA1olqTpUAJEuJsMAYB4oPieIxMAQCMAdMBsOIYJ5KRBIVBPKgwIEAO68txIjzwvlQgB0cAAkoi+Qy4KqxhIYFKYLDxKhPJobgr4Lq4NgAB5ge6MGFwvFaTDiJniCCq8R+MXQmB69hROBwAAKxBosEpWgA2jBUJIALp+M3030uCSCxJaVHvezWKRYnFUzB3bBYYD3Dal5FaAAqOd45mzEihSjIF2SZCMWj1AAoAEwAZgArDOAJScG6WbDgKgkp7BEn9Ua-Z4PNZAmJwQB8G4B2XcAsASAITJAPB-cHYQA)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/708">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/708/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/708/pledge.svg">
</picture>
</a>

**Comment by fregante** [comment]
The classic `Record & {_nominal}` allows this assignment by adding the `_nominal` property to the object 

```ts
type CustomRecord = Record<string, string | undefined> & {_nominal: undefined};
const record: CustomRecord = {foo: 'bar', _nominal: undefined};
// ✅ No assertion required
// ⚠️ _nominal property now appears at runtime
```

[TS Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwgrgZ2AewLYCUIGNkCcAmUAvFJjgQDxK4CWAdgOYA0U19DUAPlHHfhADN6EfAD4oAMigBvAPp009AIYAbAFw8+g4fgC+AbgBQOOkii5sefBvhI0ZK8RkDkyDQHIARktzuW8xTpVDV5+IToRAyA)

**Comment by fregante** [comment]
Maybe 10 years later, 2024 will be _the year:_

- https://github.com/microsoft/TypeScript/issues/202

**Comment by sindresorhus** [comment]
I think the `Label` proposal would work for you (although not as type-safe): https://github.com/sindresorhus/type-fest/issues/702

**Comment by fregante** [comment]
I need nominal types not just  labels, so unfortunately that doesn't look like it's going to work. 

I suppose the next best hope is to wait for TS to support them natively so that we don't have to use fake properties for this use.

**Comment by sindresorhus** [comment]
Maybe @ethanresnick knows.

**Comment by ethanresnick** [comment]
I think this is a TS limitation.

We could use a (rare) string as the name of the key that type-fest adds for holding the tag(s), instead of a symbol — basically undoing [this commit](https://github.com/causaly/type-fest/commit/7f63a6e7e0884cebd11b645c42a17041969add94). I think that would be a good idea, frankly, because it would make tagged types with the same tag compatible between different versions of type-fest, which is useful in some cases (esp. for companies that have utility type packages), because it's very easy for multiple copies of type-fest with different versions to slip in to a project, given npm package resolution semantics (see @spion's point [here](https://github.com/microsoft/TypeScript/issues/202#issuecomment-1442590511) and the follow up discussion). Especially given that tagged types aren't really opaque — the underlying runtime representation is still visible in the type — I think the incompatibility between type-fest versions for the same tagged type is a little weird.

However, while making the tag key a string solves this particular case, it would create a new issue where now `Record<symbol, any>` can't work with `Tagged`/`Opaque`. Granted, objects restricted to only symbol keys are much rarer, so making the tag-holding key a string would have the side benefit of making this sort of issue less common, at least. But there's no complete fix.

**Comment by ethanresnick** [comment]
To make the point above more concrete, imagine a dependency tree like:

```
@my-company/app
|__ @my-company/types@1.2.4
|__ @my-company/internal-library@1.0.0
    |__ @my-company/types@0.4.0
```

The two competing versions of the `@my-company/types` package could use different versions of `type-fest`. In that case, if the internal library returns a tagged types from the `@my-company/types` package, that tagged type may not be assignable to the "same" tag type from the version of the types package used by `@my-company/app` — _even if both versions of the type have the same tag name(s) and tag metadata_. 

Using a string in `type-fest` for the tag would solve that, essentially making two tagged types equal if they have the same base type + tag names + tag metadata (even if they came from different versions of type-fest).

**Comment by fregante** [comment]
We'll just wait for native support

- https://github.com/microsoft/TypeScript/issues/202
