### ISSUE TITLE
Why do we need to specify the `engines` field in package.json?

### ISSUE THREAD

**Issue by gavinxgu** [sindresorhus/type-fest#812]
We are currently using Node 14 in our workspace, which causes the installation of type-fest to fail. I think type-fest is just a type definition library, and it shouldn't restrict the Node version. Can we remove the engines field?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/812">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/812/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/812/pledge.svg">
</picture>
</a>

**Comment by sindresorhus** [comment]
The project requires Node.js 16. It doesn't affect the project directly, but it does avoid having to do support for npm bugs, experienced by users, that were fixed in the npm version bundled in Node.js 16, for example. And also the npm publish tool I use requires me to define it.

Node.js 14 has not been supported, even by the Node.js team, for a long time. The oldest maintained Node.js version is currently Node.js 18.
