### ISSUE TITLE
Web-specific version of `StructuredCloneable` type

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/type-fest#899]
See: https://github.com/sindresorhus/type-fest/pull/897#issuecomment-2189741111

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/sindresorhus) so you can upvote and help fund this issue.
- The funding will be given to active contributors.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/sindresorhus/type-fest/issues/899">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sindresorhus/type-fest/issues/899/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sindresorhus/type-fest/issues/899/pledge.svg">
</picture>
</a>

**Comment by AviVahl** [comment]
The current version requires dom types: https://github.com/wixplosives/pleb/actions/runs/9767856252/job/26964079939?pr=732

Given this issue I'm not sure whether this was an oversight or done on purpose.

**Comment by AviVahl** [comment]
Or maybe File is only available with newer Node types. I use @types/node 18.x

**Comment by AviVahl** [comment]
Yep, newer @type/node@20 work. Sorry for the confusion.

**Comment by Emiyaaaaa** [comment]
@thecodewarrior

**Comment by Emiyaaaaa** [comment]
@sindresorhus Should we add @types/node 20 in package dependence, or remove `File` and `Blob` that depend on @types/node?

**Comment by sindresorhus** [comment]
I think it's ok to keep those as they are available in both Node.js and browsers.

**Comment by Emiyaaaaa** [comment]
> I think it's ok to keep those as they are available in both Node.js and browsers. We should not add `@types/node` as a dependency.

But if user not install the `@types/node` or `@types/node` version less than 20, thay will get that error https://github.com/wixplosives/pleb/actions/runs/9767856252/job/26964079939?pr=732

So I think we should specify `@types/node`20 in dependencies. or remove `File` and `Blob` that require the `@types/node`.

**Comment by thecodewarrior** [comment]
We could probably add `@types/node` v20+ as an [optional peer dependency](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#peerdependenciesmeta)

Something like this:
```json
{
  "peerDependencies": {
    "@types/node": ">=20"
  },
  "peerDependenciesMeta": {
    "@types/node": {
      "optional": true
    }
  }
}

**Comment by tao-cumplido** [comment]
> > I think it's ok to keep those as they are available in both Node.js and browsers. We should not add `@types/node` as a dependency.
> 
> But if user not install the `@types/node` or `@types/node` version less than 20, thay will get that error https://github.com/wixplosives/pleb/actions/runs/9767856252/job/26964079939?pr=732
> 
> So I think we should specify `@types/node`20 in dependencies. or remove `File` and `Blob` that require the `@types/node`.

I ran into this error and don't even use the `StructuredCloneable` type. I am writing a library that uses neither the DOM nor `@types/node` definitions. But since the `StructuredCloneable` is exported from `index.ts`, TS errors on not finding `Blob` nor `File`. Had to revert to `~4.20.1` for now.

**Comment by voxpelli** [comment]
Having same issue as @tao-cumplido – most my projects are currently failing type checks due to this.

Since the major version of `@types/node` adheres to the major version of node.js and since `type-fest` supports node.js `>=16` it can't reference the `File` as neither `@types/node@^16` or `@types/node@^18` references it.

https://github.com/sindresorhus/type-fest/blob/60712f1d667a88dc2e3ae846281dd852f1303ac0/package.json#L16

Since most of my projects still support Node.js 18 I use `@types/node@^18` in them, to get the types of the oldest version in my support range, and since I don't use `skipLibCheck` (classic reference to https://github.com/sindresorhus/tsconfig/issues/15 / https://github.com/voxpelli/tsconfig/issues/1) I get this issue, just like eg. @tao-cumplido and @AviVahl gets

(Also reminds me of https://github.com/sindresorhus/type-fest/issues/809, which I guess is a bigger issue for those of us that don't use `skipLibCheck`, as we get struck by issues like this, and I can't use `skipLibCheck` as I need the `.d.ts` files that I write myself to be validated)
